---
title: "ReadMe"
author: ICES
date: 5th Novrember 2016
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Oxygen Debt Indicator Calculation Scripts

The following as an example of fitting the HEAT oxygen debt profile models to CTD or water bottle data.  The code below assumes that the repository has been cloned, and that the data has been downloaded and prepared via.  This will create the folder `model` and the file `model/input.csv'

```{r input, echo=TRUE, eval=FALSE}
source("scripts/OxygenDebt/01_input.R")
```


```{r oxysetup, echo = FALSE, message = FALSE}
library(oxydebt)
oxy <- read.csv("../../model/input.csv")
```


```{r example_norun, eval=FALSE}
# load libraries
library(oxydebt)

# read in data
oxy <- read.csv("model/input.csv")
```



```{r example_run}
# inspect the results from one fit
ID <- 8492
data <- oxy[oxy$ID == ID,]
fit <- doonefit_full(data, ID = ID)

p <- plot_fit(fit, data)
print(p)
```

